# Generated by Django 4.2.13 on 2024-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceNorms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('value_man', models.CharField(max_length=255, verbose_name='Норма для мужчин')),
                ('value_woman', models.CharField(max_length=255, verbose_name='Норма для женщин')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reasons', models.TextField(verbose_name='Причины отклонения')),
                ('conclusion', models.TextField(verbose_name='Заключение')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='Сгенерировано ИИ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Нормы',
                'verbose_name_plural': 'Нормы',
                'ordering': ['name'],
            },
        ),
    ]
