FROM python:3.9-slim

WORKDIR /app/bot

RUN apt-get update
RUN apt-get install -y poppler-utils
RUN rm -rf /var/lib/apt/lists/*

COPY requirements/bot.txt ./reqs.txt
RUN pip install --upgrade pip
RUN pip install -r reqs.txt

COPY ./bot .

CMD python main.py
