FROM python:3.9-slim

WORKDIR /app/bot

RUN apt-get update
RUN apt-get install -y poppler-utils
RUN apt-get install -y tesseract-ocr
RUN apt-get install -y tesseract-ocr-rus

RUN pip install --upgrade pip

COPY requirements/bot.txt ./reqs.txt
RUN pip install -r reqs.txt

COPY ./bot .

CMD python main.py
